pool:
  vmImage: ubuntu-latest

trigger:
- main

steps:
- task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
  inputs:
    ignoreDirectories: 'src'
