# [Choice] Ubuntu OS version (use focal or jammy on local arm64/Apple Silicon): bionic, focal, jammy
ARG VARIANT="jammy"
FROM swift:${VARIANT}

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>