name: Smoke test "javascript-node" build

on: 
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    paths:
      - src/javascript-node/**
      - .github/workflows/smoke-javascript-node.yaml
      - .github/actions/**
      - build/**
jobs:
  smoke-test:
    name: Smoke test
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      id: checkout
      uses: actions/checkout@v3

    - name: Smoke test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: smoke_test
      uses: ./.github/actions/smoke-test
      with:
        image: javascript-node
